import Stripe from 'stripe';

export const mockPrice: Stripe.Price = {
  id: 'price_12345',
  object: 'price',
  active: true,
  billing_scheme: 'per_unit',
  created: 1672531200,
  currency: 'usd',
  custom_unit_amount: null,
  livemode: false,
  lookup_key: null,
  metadata: {},
  nickname: 'Test Price',
  product: 'prod_12345',
  recurring: null,
  tax_behavior: 'unspecified',
  tiers_mode: null,
  transform_quantity: null,
  type: 'one_time',
  unit_amount: 1000,
  unit_amount_decimal: '1000',
};

export const mockProduct: Stripe.Product = {
  id: 'prod_12345',
  object: 'product',
  active: true,
  created: 1672531200,
  default_price: 'price_12345',
  description: 'A test product',
  images: [],
  livemode: false,
  metadata: {
    credits: '100',
  },
  name: 'Test Product',
  package_dimensions: null,
  shippable: null,
  statement_descriptor: null,
  tax_code: null,
  type: 'service',
  unit_label: null,
  updated: 1672531200,
  url: null,
  features: [],
};
