import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ErrorSuppressor } from "@/components/ErrorSuppressor";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/hooks/useAuth";
import { CreditProvider } from "@/hooks/useCredits";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ErrorSuppressor />
        <AuthProvider>
          <CreditProvider>
            {children}
          </CreditProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
